services:
- docker
script:
- docker build -t godev-docker .
- docker login --username vltraheaven --password $DOCKER_PASSWD
- docker tag godev-docker:latest vltraheaven/godev-docker
- docker push vltraheaven/godev-docker:latest